Feature/part one
nightlaro/Listmaker pull request #1
Opened 2021-07-19 22:15 UTC by nightlaro

- Will render a hard coded todo list

2021-07-19 23:16 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/MainActivity.kt
> +        todoListRecyclerView.adapter = ToDoListAdapter()
if you're not using `toDoListRecyclerView` anywhere else, there's not need to make it a class var.
Generally, we want to avoid `var` and `lateinit` if possible.

2021-07-19 23:17 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/ToDoListAdapter.kt
> +
also feel free to nest `ToDoListViewHolder` inside of the adapter class. That's how most people do it, and it's convenient to have the classes in one file

2021-07-19 23:17 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/ToDoListViewHolder.kt
> +    var listTitleTextView = itemView.findViewById<TextView>(R.id.itemString)
use `val` instead of var

2021-07-19 23:19 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/ToDoListAdapter.kt
> +    private val toDoList = arrayOf("Android Development", "House work", "Errands")
generally it's discouraged to use `arrayOf`. Use `listOf` or `mutableListOf`; that way it's explicit if you want it to be mutable or not

2021-07-19 23:24 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/ToDoListAdapter.kt
> +class ToDoListAdapter: RecyclerView.Adapter<ToDoListViewHolder>() {
improper formatting. There should be a space between the class and the colon: 
`ToDoListAdapter : RecyclerView.Adapter<ToDoListViewHolder>()"
The convention is if there's no space, you're signifying the type. If there's a space, you're signifying inheritance.
i.e.
```
//type
val adapter: ToDoListAdapter

//inheritance
class ToDoListAdapter : RecyclerView.Adapter()
```

2021-07-19 23:24 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/ToDoListViewHolder.kt
> +class ToDoListViewHolder(itemView: View): RecyclerView.ViewHolder(itemView) {
wrong formatting here, too. You need a space before the colon

2021-07-19 23:25 UTC, vaudevillen requested changes
just some minor things. looks good, otherwise.

2021-07-20 00:08 UTC, asarazan commented on app/src/main/java/com/nightlaro/listmaker/ToDoListAdapter.kt
> +class ToDoListAdapter: RecyclerView.Adapter<ToDoListViewHolder>() {
TIL

2021-07-21 20:37 UTC, merged