Feature/part three
nightlaro/Listmaker pull request #5
Opened 2021-07-23 18:43 UTC by nightlaro

2021-07-23 23:42 UTC, asarazan commented on app/src/main/java/com/nightlaro/listmaker/DetailActivity.kt
> +    lateinit var list : Tasklist
If you wanna get fancy, try:
```kt
val list by lazy {
  intent.getParcelableExtra<Tasklist>(MainActivity.INTENT_LIST_KEY)
}
```

2021-07-23 23:43 UTC, asarazan commented on app/src/main/java/com/nightlaro/listmaker/DetailActivity.kt
> +    lateinit var list : Tasklist
(this may very well be skipping some chapters)

2021-07-23 23:45 UTC, asarazan commented on app/src/main/java/com/nightlaro/listmaker/MainActivity.kt
> +        const val LIST_DETAIL_REQUEST_CODE = 420
🌲 🔥

2021-07-23 23:47 UTC, asarazan commented on app/src/main/java/com/nightlaro/listmaker/MainActivity.kt
> +        todoListRecyclerView.adapter = ToDoListAdapter(lists, this) //refreshes recycler view
Creating a new adapter because you need to change the list seems... off to me-- at least as long as the list itself is mutable. Maybe change `addList` to `setList` and use that instead?

2021-07-23 23:48 UTC, asarazan commented on app/src/main/java/com/nightlaro/listmaker/MainActivity.kt
> +        todoListRecyclerView.adapter = ToDoListAdapter(lists, this) //refreshes recycler view
And I would still probably make the inner list itself immutable for good measure.

2021-07-23 23:50 UTC, asarazan commented on app/src/main/java/com/nightlaro/listmaker/MainActivity.kt
> +    private fun showTaskListItems(list : Tasklist) {
One thing I like to do when dealing with intents is to create a launch function on the activity class's companion object-- something like:
```kt
class DetailActivity ... {
  companion object {
    fun launch(context: Context, list: Tasklist) {
      // Lines 104-106 go here.
    }
  }
}
```

This allows you to make the activity launch flow a little more typesafe, as you can now just call `DetailActivity.launch(this, list)`

2021-07-23 23:52 UTC, asarazan approved these changes
Feel free to take or leave my crazy suggestions :-)

2021-07-26 17:15 UTC, vaudevillen commented on app/src/main/AndroidManifest.xml
> +            android:exported="true" />
how come you added `android:exported="true"`? According to the docs, this makes it possible for other apps to call this activity.

2021-07-26 17:16 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/DetailActivity.kt
> +    lateinit var addTaskButton: FloatingActionButton
all these vars can be `private`

2021-07-26 17:17 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/DetailActivity.kt
> +        Intent().apply {
ooooh, so fancy with that `apply`

2021-07-26 17:57 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/MainActivity.kt
> +    }
for convention, we put the companion object at the top of the class. (I've seen it put at the bottom, too. But the point is we should keep it separate for organization purposes)

2021-07-26 17:57 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/MainActivity.kt
> +    }
also the `val datamanager` and `var todoListRecyclerView` should be private

2021-07-26 18:07 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/Tasklist.kt
> +               val tasks: MutableList<String> = mutableListOf()): Parcelable {
Does this need to be mutable? Avoid mutability if you can.

2021-07-26 18:09 UTC, nightlaro commented on app/src/main/AndroidManifest.xml
> +            android:exported="true" />
> how come you added `android:exported="true"`? According to the docs, this makes it possible for other apps to call this activity.

AH didn't realize, I just left it as is from auto generation by android studio

2021-07-26 18:11 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/Tasklist.kt
> +               val tasks: MutableList<String> = mutableListOf()): Parcelable {
if you need to tweak something in the data class, you can always use the `copy` function to copy the original values but also be able to change individual properties. remember the `Movie` example from a couple lessons back?

2021-07-26 18:19 UTC, vaudevillen requested changes
Dude, looking pretty good so far. Just a few changes necessary:
- getting rid of that `exported` tag from the manifest
- resetting the list in the adapter instead of creating a new one
- and changes those public `val/var`s to `private`
- getting rid of the `mutable` lists.

2021-07-26 19:24 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/DetailActivity.kt
> +            setResult(Activity.RESULT_OK, intent)
okay, so I don't think this is doing what you think it's doing.

`setResult` is a method on the `activity`, so putting this in the `apply` block is confusing. It's like, are you using this method on the `intent` or the `activity`. Also, the intent you're giving to `setResult` isn't the same intent you just created. Essentially, you're giving it the same intent that you created this activity with.

2021-07-26 20:21 UTC, nightlaro commented on app/src/main/java/com/nightlaro/listmaker/DetailActivity.kt
> +    lateinit var list : Tasklist
> If you wanna get fancy, try:
> 
> ```kotlin
> val list by lazy {
>   intent.getParcelableExtra<Tasklist>(MainActivity.INTENT_LIST_KEY)
> }
> ```

Yep, Josh showed me this -- also is it safe to say to try to avoid `by lazy` as much as possible because of performance impact?

2021-07-26 20:49 UTC, asarazan commented on app/src/main/java/com/nightlaro/listmaker/DetailActivity.kt
> +    lateinit var list : Tasklist
I would actually say the opposite is usually true, unless I'm missing some context here. @vaudevillen?

2021-07-26 23:47 UTC, nightlaro commented on app/src/main/java/com/nightlaro/listmaker/Tasklist.kt
> +               val tasks: MutableList<String> = mutableListOf()): Parcelable {
> Does this need to be mutable? Avoid mutability if you can.

I would say I do need this to be mutable because, in `DetailActivity` line 67, I am adding `tasks` inside of this `toDo` (`Tasklist.name`)

It may be possible to create a method inside of `Tasklist` to utilize `copy` and overwrite the `key`'s value

2021-07-27 01:25 UTC, nightlaro commented on app/src/main/java/com/nightlaro/listmaker/MainActivity.kt
> +        todoListRecyclerView.adapter = ToDoListAdapter(lists, this) //refreshes recycler view
I have attempted to do this, but seems like I was having positioning issue for my adapter... view holder? I'll give this another go

2021-07-27 17:09 UTC, asarazan commented on app/src/main/java/com/nightlaro/listmaker/MainActivity.kt
> +        todoListRecyclerView.adapter = ToDoListAdapter(lists, this) //refreshes recycler view
So he is using `notifyItemInserted` which theoretically should be fine given that he only supports additions? However there is the longer-term maintenance concern around doing any operation that is not addition

2021-07-27 17:09 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/Tasklist.kt
> +               val tasks: MutableList<String> = mutableListOf()): Parcelable {
you should notice that `list`, the object you're updating in `DetailActivity` is mutable. You can set it with a new instance of `TaskList`

2021-07-27 17:13 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/DetailActivity.kt
> +    lateinit var list : Tasklist
Yeah, this isn't something we should be worried about. I had heard that with lazy delegates, there's additional space overhead because it's creating anonymous classes. But that's not something we need to worry about unless we're doing a whole bunch of other things wrong.

2021-07-28 01:00 UTC, nightlaro commented on app/src/main/java/com/nightlaro/listmaker/DetailActivity.kt
> +                taskListRecyclerView.adapter = TaskListAdapter(list) //Yeah... :c
Any opinion on this? When I was adding tasks into a Todo... my tasks weren't showing up anymore as I add them, it would only show up if I press back and tap the Todo again

It seems like doing this fixed that problem, it's now showing me my tasks as I add them -- Is this a janky way of doing it?

I tried `taskListRecyclerView.adapter.notifyDataSetChanged()` but that didn't really work either

2021-07-28 17:21 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/DetailActivity.kt
> +                taskListRecyclerView.adapter = TaskListAdapter(list) //Yeah... :c
yeah, this isn't the best way to go about it. There's a lot of extra overhead if you're creating a new adapter every time. We can pair on this again

2021-07-28 17:22 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/Tasklist.kt
> +    //no clue what this parcel thing is doing at this moment
that's okay. You'll understand this more later. Just know that this is a way to serialize/deserialize data.

2021-07-28 17:23 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/ToDoListAdapter.kt
> +        Log.d("Something_COOL", "onBindViewHolder $position HASHCODE: ${holder.hashCode()}")
Need to get rid of these dev logs

2021-07-28 17:29 UTC, asarazan commented on app/src/main/java/com/nightlaro/listmaker/ToDoListAdapter.kt
> +        Log.d("Something_COOL", "onBindViewHolder $position HASHCODE: ${holder.hashCode()}")
But how will people know it's COOL?

2021-07-28 17:35 UTC, vaudevillen commented on app/src/main/java/com/nightlaro/listmaker/ToDoListAdapter.kt
> +        Log.d("Something_COOL", "onBindViewHolder $position HASHCODE: ${holder.hashCode()}")
oh shoot, good point

2021-08-23 18:09 UTC, asarazan commented
Now that we're all back, are we good to close this out?

2021-08-23 18:27 UTC, merged